export const cryptoData = [
  {
    name: 'Bitcoin',
    ticker: 'BTC',
    description: 'The first decentralized digital currency, created in 2009. It operates on a peer-to-peer network without the need for a central authority.',
    marketCap: '1.3T',
    price: 68000,
    volume24h: '25B',
    noveltyScore: 0.1,
  },
  {
    name: 'Ethereum',
    ticker: 'ETH',
    description: 'A decentralized platform that runs smart contracts: applications that run exactly as programmed without any possibility of downtime, censorship, fraud or third-party interference.',
    marketCap: '450B',
    price: 3800,
    volume24h: '15B',
    noveltyScore: 0.3,
  },
  {
    name: 'Solana',
    ticker: 'SOL',
    description: 'A high-performance blockchain supporting builders around the world creating crypto apps that scale today. Known for its speed and low transaction costs.',
    marketCap: '75B',
    price: 165,
    volume24h: '3B',
    noveltyScore: 0.7,
  },
  {
    name: 'Aetherium',
    ticker: 'AETH',
    description: 'A novel layer-3 scaling solution for Ethereum focusing on decentralized AI computation. It allows for complex AI models to run on-chain.',
    marketCap: '500M',
    price: 2.5,
    volume24h: '50M',
    noveltyScore: 0.95,
  },
  {
    name: 'Quantum Core',
    ticker: 'QTC',
    description: 'A cryptocurrency project aiming to build a quantum-resistant blockchain. It uses a novel cryptographic algorithm to protect against future threats.',
    marketCap: '250M',
    price: 15,
    volume24h: '20M',
    noveltyScore: 0.98,
  },
  {
    name: 'Cardano',
    ticker: 'ADA',
    description: 'A proof-of-stake blockchain platform that says its goal is to allow “changemakers, innovators and visionaries” to bring about positive global change.',
    marketCap: '16B',
    price: 0.45,
    volume24h: '400M',
    noveltyScore: 0.4,
  },
  {
    name: 'Ripple',
    ticker: 'XRP',
    description: 'A digital payment protocol and cryptocurrency. It is designed for fast and low-cost international payments for financial institutions.',
    marketCap: '29B',
    price: 0.52,
    volume24h: '1.2B',
    noveltyScore: 0.2,
  },
  {
    name: 'Dogecoin',
    ticker: 'DOGE',
    description: 'A peer-to-peer, open-source cryptocurrency. It is considered an altcoin and an almost sarcastic meme coin.',
    marketCap: '23B',
    price: 0.16,
    volume24h: '900M',
    noveltyScore: 0.1,
  },
  {
    name: 'Celestia',
    ticker: 'TIA',
    description: 'A modular data availability network that securely scales with the number of users, making it easy for anyone to launch their own blockchain.',
    marketCap: '2B',
    price: 10.5,
    volume24h: '150M',
    noveltyScore: 0.9,
  },
  {
    name: 'Helium',
    ticker: 'HNT',
    description: 'A decentralized blockchain-powered network for Internet of Things (IoT) devices. It allows low-powered wireless devices to communicate with each other.',
    marketCap: '900M',
    price: 5.5,
    volume24h: '30M',
    noveltyScore: 0.8,
  },
  {
    name: 'Render Token',
    ticker: 'RNDR',
    description: 'A distributed GPU rendering network built on top of the Ethereum blockchain, aiming to connect artists and studios in need of GPU compute power.',
    marketCap: '3.8B',
    price: 10,
    volume24h: '200M',
    noveltyScore: 0.85,
  },
  {
    name: 'SingularityNET',
    ticker: 'AGIX',
    description: 'A decentralized marketplace for AI services. It allows anyone to create, share, and monetize AI services at scale.',
    marketCap: '1.2B',
    price: 0.9,
    volume24h: '100M',
    noveltyScore: 0.88,
  },
  {
    name: 'zkSync',
    ticker: 'ZK',
    description: 'A Layer-2 scaling solution that uses zero-knowledge rollups to bring massive scalability and low transaction fees to Ethereum.',
    marketCap: '700M',
    price: 0.2,
    volume24h: '800M',
    noveltyScore: 0.92,
  },
  {
    name: 'Starknet',
    ticker: 'STRK',
    description: 'A decentralized Validity-Rollup (aka ZK-Rollup). It operates as a Layer 2 network over Ethereum, enabling dApps to achieve massive scale for their computation.',
    marketCap: '900M',
    price: 1.25,
    volume24h: '120M',
    noveltyScore: 0.91,
  },
  {
    name: 'Veridia',
    ticker: 'VRD',
    description: 'A new blockchain focused on tokenizing real-world green energy assets. It aims to create a transparent and liquid market for renewable energy credits.',
    marketCap: '80M',
    price: 0.5,
    volume24h: '5M',
    noveltyScore: 0.97,
  },
  {
    name: 'Polkadot',
    ticker: 'DOT',
    description: 'A sharded multichain protocol that connects and secures a network of specialized blockchains, facilitating cross-chain transfer of any data or asset types.',
    marketCap: '10B',
    price: 7.2,
    volume24h: '250M',
    noveltyScore: 0.6,
  },
  {
    name: 'Chainlink',
    ticker: 'LINK',
    description: 'A decentralized oracle network that provides real-world data to smart contracts on the blockchain.',
    marketCap: '10.5B',
    price: 17.5,
    volume24h: '400M',
    noveltyScore: 0.5,
  },
  {
    name: 'Avalanche',
    ticker: 'AVAX',
    description: 'A layer one blockchain that functions as a platform for decentralized applications and custom blockchain networks. It is one of Ethereum’s rivals.',
    marketCap: '14B',
    price: 36,
    volume24h: '500M',
    noveltyScore: 0.65,
  },
  {
    name: 'Shiba Inu',
    ticker: 'SHIB',
    description: 'A meme coin that has transformed into a decentralized ecosystem. It was created as an "experiment in decentralized spontaneous community building".',
    marketCap: '15B',
    price: 0.000025,
    volume24h: '800M',
    noveltyScore: 0.15,
  },
  {
    name: 'ChronoSynth',
    ticker: 'CSYN',
    description: 'A decentralized protocol for temporal asset management, allowing users to trade and speculate on the future value of digital assets using time-locked contracts.',
    marketCap: '45M',
    price: 1.10,
    volume24h: '8M',
    noveltyScore: 0.99,
  }
];
